#!/bin/bash

python3 -m project3.get_output
latexmk -pdf CurveInterpolation/curve_interpolation.tex
latexmk -c CurveInterpolation/curve_interpolation.tex
mv curve_interpolation.pdf ./output/report/report.pdf

zip -r output output --exclude **/__MACOSX
